name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install dvc
      - name: Download data
        run: |
          dvc pull
      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest tests/
